name: 🧪 Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
       java-version: 21
       distribution: 'temurin'
       cache: 'maven'
    - run: mvn -B test
